### ISSUE TITLE
Refactor to support multiple Indices 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#101]
Maestro right now is target toward indexing a single index, `file_centric`.  This means that many of the functions and classed are not prepared to work within the scope of a second index type - they are only programmed to work with a `file_centric` view. 

Thus, we need to adjust the code in maestro to be able to respond to a multi-index structure. 

- refactor DefaultIndexer to remove the duplication of code
- refactor FileCentricElasticSearchAdapter + AnalysisCentricElasticSearchAdapter to be combined into a single adapter

**Comment by Buwujiu** [comment]
Under PR #99: https://github.com/overture-stack/maestro/pull/99
