### ISSUE TITLE
Refactor Maestro so that event processing can respond to multiple index types 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#102]
We need to update these classes to update the logic to handle `file_centric` and `analysis_centric`.  Currently there one topic for all.  The event processing logic needs to updated to process both `file_centric` and `analysis_centric` outputs. 

- refactor SongAnalysisStreamListener to use indexAnalysis()
- refactor IndexingMessagesStreamListener

**Comment by Buwujiu** [comment]
Under PR #99: https://github.com/overture-stack/maestro/pull/99
