### ISSUE TITLE
BUG - Issues in file_centric index

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#113]
## Environment 
Testing on rdpc dev environment

Based on the agreed schema which was reviewed : 
https://github.com/icgc-argo/argo-metadata-schemas/blob/master/mappings/maestro_file_centric.json 

## Top level field issues:
- [ ] `data_type` is missing
- [ ] `file` is misnamed to `files`

## Analysis field issues:
- state is included in `file-centric` in index, but not in mapping.  I think we need this, so mapping needs update
- `variant_class` isn't defined in the mapping.. so why is it here?
- `study_id` is under analysis.  This is not in the mapping... so why is it in index?
- there are additional fields which are not defined as part of mapping:
-- "platform_model": "HiSeq 2000",
-- "sequencing_date": "2014-12-12",
-- "sequencing_center": "EXT",
-- "experimental_strategy": "WGS",
-- "submitter_sequencing_experiment_id": "TEST_EXP"

## Donor field issues:
- [ ] type `nested`  fields are not all wrapped in the square bracket `[ ]` array indicators
--- nested fields are `donor`, `specimen`, `sample`, `repositories`
--- `sample` and `specimen` are not correctly formatted
![image](https://user-images.githubusercontent.com/15824252/81837925-76e72b00-9513-11ea-8d25-2ce2fd98ff66.png)

## Repository field issues
- [ ] There are several additional fields defined that the mapping does not have:
- "data_path": "/score-rdpc-collab-dev/data",
- "metadata_path": "/score-rdpc-collab-dev.state/data/"
- type 
 
### OTHER ISSUES:
Look at this document:  "_id": "58a179b6-cf20-57a6-a9fe-bc05049fc2fe",
^ index files are not being nested within their parent file document (`index_file`), but instead are being inserted as regular file documents
- BAMs have BAIs
- CRAMs have CRAI
- VCF have TBI

**Comment by Buwujiu** [comment]
Regarding `Repository field issues`, will remove `data_path` and `metadata_path` from `repositories`.
