### ISSUE TITLE
IntelliJ - Tests Not Found

### ISSUE THREAD

**Issue by lepsalex** [overture-stack/maestro#117]
**Problem**
Running the latest IntelliJ (2020.1) on linux/windows will result in a "tests not found" bug when running package tests. Individual test cases do run but even the encompassing test class is unable to run its own test cases.

**Temp Workaround**
Downgrading JUnit to version `5.5.2` resolves this issue but it is unclear as to where the conflict is, this is most likely a bug in IntelliJ but it could be something in this repo as well.

**Comment by lepsalex** [comment]
After speaking with Bashar it seems that this is potentially a conflict between Spring boot test starter and the current junit, spring boot test it imports junit 5.5.2

**Comment by blabadi** [comment]
fixed by downgrading
