### ISSUE TITLE
Feature Request: Allow Indexing of `base schema` info fields similar to dynamic fields 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#138]
Info fields are available on these base schema entities:
- specimen, 
- sample, 
- donor
- file

We need to create a rule that maestro can follow for all info fields. 

## Possible Implementations

1.  `fields should always be included in the exact structure of the info field in the mapping, including the  info object`

2. `field in an info object will always be added to the root level of the object they belong to`

**Comment by rosibaj** [comment]
@blabadi this is done right?

**Comment by blabadi** [comment]
yeah this is done, unless there is a bug it can be closed
