### ISSUE TITLE
Add variant_class to file_centric mapping

### ISSUE THREAD

**Issue by Buwujiu** [overture-stack/maestro#142]
As discussed in this ticket https://github.com/icgc-argo/argo-metadata-schemas/issues/32, field `variant_class` is needed for file_centric index mapping.

`variant_class` is only available in song payload when analysis type is `variant_calling`, the field should be `null` when there is no `variant_class` in song. 

analyses with variant_class: https://song.rdpc-qa.cancercollaboratory.org/studies/OCCAMS-GB/analysis?analysisStates=PUBLISHED

**Comment by blabadi** [comment]
isn't this a dynamic field ?
