### ISSUE TITLE
Expose Maestros Analysis -- File Logic as an API

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#165]
Maestro accepts a list of analyses and transforms them to the file centric document

need to provide this functionality as an API endpoint - same functionality, new delivery

**Comment by blabadi** [comment]
swagger: https://maestro.qa.argo.cancercollaboratory.org/api-docs

![image.png](https://images.zenhubusercontent.com/5c99083bd2fde800015cf9fa/82ff7a3e-acfd-48b0-9762-c1bf0b95a12f)

repo code for qa is `song.collab`

**Comment by rosibaj** [comment]
Tested with curl --location --request GET 'https://song.rdpc-qa.cancercollaboratory.org/studies/OCCAMS-GB/analysis/c7600354-09ae-45be-a003-5409ae65beb2' \ 

- conversion returned 6 expected filed from one qc_analyss

Tested with curl --location --request GET 'https://song.rdpc-qa.cancercollaboratory.org/studies/OCCAMS-GB/analysis/636e1b59-7618-4efd-ae1b-597618aefdba' \
- returned only one fiel document (expected as index file should not be indexed)

Tested with an arrany of both of these analyses and got the expected file documents for each analysis. 

thanks @blabadi !
