### ISSUE TITLE
Update Song event processing to consume full analysis payload

### ISSUE THREAD

**Issue by blabadi** [overture-stack/maestro#167]
Song will be providing full payload for analyses in its events (https://github.com/overture-stack/SONG/issues/674)
we need to adopt maestro to consume full messages instead of reaching out to song

## Detailed Description

currently song provides analysis Id and repo code and study id
then maestro reaches to song and fetch the rest of the data
when song provides the full analysis payload no need to do that anymore

**Comment by rosibaj** [comment]
@blabadi @joneubank i believe this is already taken care of - can  you confirm?

**Comment by rosibaj** [comment]
@blabadi was this completed with Maestro, or is this outstanding?

**Comment by blabadi** [comment]
> @blabadi was this completed with Maestro, or is this outstanding?

as far as I know this is not implemented in maestro yet, to avoid calling song on event based indexing

**Comment by rosibaj** [comment]
thanks for confirming @blabadi !

**Comment by b-f-chan** [comment]
Moving to latest sprint for @b-f-chan to finish testing
