### ISSUE TITLE
DAC backups audit and recovery testing

### ISSUE THREAD

**Issue by yalturmes** [overture-stack/maestro#247]
Original request from Bashar:
Devops to confirm on the production environment that DAC backups/restoration (db & collab bucket) functionality, keys, are all working just to make sure everything is ready, we will need this confirmation before the 28th of April.

- [x] S3 object store recovery testing performed
- [x] Mongodb recovery testing performed
- [x] S3 object store recovery documented
- [x] Mongodb recovery testing documented

**Comment by yalturmes** [comment]
Created a wiki to document recovery process for both mongodb and s3 files:
https://wiki.oicr.on.ca/pages/viewpage.action?pageId=191466496
The process for mongodb recovery has been documented.

**Comment by b-f-chan** [comment]
Might need @henro001 help with the S3 documentation
