### ISSUE TITLE
Conflict Resolution 

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#25]
What happens when 2 records do not match in  2 repositories? 

**Expected Behaviour**
------
If the data of the same Analysis-ID does not match in two different song repositories, then:
1. The analysis document should be deleted from the index.
2. An alert for data-conflict-resolution should be sent to a message queue recording the repository and both analysis ids (is there a unique SONG record id for each of these as well?) 

Critera to delete a record - 
All fields _must_ have the exact same value EXCEPT for date-time values like `created_date` or `updated_date` OR the `info` fields. If they have a single field that does not match, then delete the record.

**Comment by christinayung** [comment]
Unless there's a timestamp on when the analysis is last updated/uploaded, I think all the fields should be the same.  This expected behavior looks good.

**Comment by blabadi** [comment]
Documenting a discussion that came up:

Song A (primary) - Song B

Problem with the current approach
if song A index a file then song B tries to index an invalid version of the file then maestro deletes the original file.
if song B tries again they will succeed.


The suggested approach is :
- maestro is not the best place to govern data consistency in songs and it also can't force integrity on scores.
- have a primary correct source (song A) for truth if changes are needed on an analysis files it has to happen there first. the others are mirrors that should reflect it.
- have a reference field in each mirror that refer to the primary to be used to validate files and reference check if it has latest version.
- that primary song has the priority to update the index, mirrors should only update the repository fields.
- mirrors listen to events from their primary songs and update their copied versions accordingly & automatically.
@rosibaj feel free to correct me or add things
