### ISSUE TITLE
Kubernetes Upgrade

### ISSUE THREAD

**Issue by puneet-oicr** [overture-stack/maestro#257]
Due by December 4th, 2022.

Must include:
Priority 1 - Backups? Apps and services
Priority 2 - Upgrade helm charts
Priority 3 - Upgrade apps/services 
Application Upgrade - Song, Score, Song DB
Infrastructure Services - CertManager
Establish a download test for Azure dev

**Comment by jmimico** [comment]
I think this ticket was created in the wrong repo and if this pertains to upgrading Azure k8s clusters, we had a ticket for this and the work was completed last week. https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/cancercollaboratory/infra/300

**Comment by puneet-oicr** [comment]
Thank you Jared! Yes, I made a error. Deleting this.
