### ISSUE TITLE
Spin-up Arranger to review indices

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#5]
- add to a vm for review

**Comment by blabadi** [comment]
arranger + indexer deployed on a vm (reachable from office only) now and accessible here (go to portal, there is one index):
http://142.1.177.110:8080

you can index studies (from song.cancercollaborartory.org, replace study place holder) using this command:
```curl -X POST \
  http://142.1.177.110:11235/index/repository/collab/study/<<study>> \
  -H 'Content-Type: application/json' \
  -H 'cache-control: no-cache'```
