### ISSUE TITLE
Maestro Dynamic Song Schema Update

### ISSUE THREAD

**Issue by rosibaj** [overture-stack/maestro#72]
Changes needed for Maestro:

Background:
The dynamic schema portion in SONG is called `data`, maestro needs to read the`data` portion in order to index analyses, studies, and repositories. 

`experiment` is a required field, other fields under `data` are optional depending on the schema. 
Example, the `data` field could be:
```
"data" : {
  "experiment" : {  "myField1": "" },
  "myField2" : {.....},
  "myField3" {......},
  }
}
```
To do:
- update `FileCentricAnalysis` model to use type : {name, version}
- update `FileCentricAnalysis` model, by replacing experiment field with `data` which will include the dynamic data portion
- update `FileCentricDocumentConverter.java ` . `getExperiement` method, to be `getData` method

**Comment by Buwujiu** [comment]
Resolving kafka port forward network issue, will continue working on Oct. 14.

**Comment by blabadi** [comment]
elastic server url : http://es.qa.argo.cancercollaboratory.org/
kafka ui (to see song messages): https://kafka-ui.qa.argo.cancercollaboratory.org/#/cluster/default/topic/n/song-analysis/data/table
